# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HenrikOs < Formula
  desc "Mac development environment setup CLI"
  homepage "https://github.com/henrikkvamme/henrik-os"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/henrikkvamme/henrik-os/releases/download/v0.1.0/henrik-os_0.1.0_darwin_amd64.tar.gz"
    sha256 "3d075855742fbb4eebb46290bc7187216ea0fa2f341447defd8bcffce077c39a"

    def install
      bin.install "henrik-os"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/henrikkvamme/henrik-os/releases/download/v0.1.0/henrik-os_0.1.0_darwin_arm64.tar.gz"
    sha256 "d61bb0fb6ec5ac80736c05e29708f5cfbecb596a9196c6521b08fd6c4421d8b1"

    def install
      bin.install "henrik-os"
    end
  end
end
